#docker-compose -f docker-compose-preprod.yml up
version: '3'
services:
  www:
    build:
      context: ../
      dockerfile: ./Docker/apache/Dockerfile
    ports:
      - 81:80
    volumes:
      - ../:/var/www/html
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=videgrenierenligne
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8101:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
